---
name: Render README.md

on:
  workflow_dispatch:
  push:
    branches:
    - main
    paths:
    - '.github/scripts/render_readme.py'
    - 'templates/README.md.j2'
    - 'data.json'

jobs:
  render-readme:
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r .github/scripts/requirements.txt

    - name: Run script
      id: run
      run: |
        python .github/scripts/render_readme.py > README.md

    - name: Commit and push updated badges
      run: |
        if [[ -n $(git status --porcelain) ]]; then
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git pull
          git add "README.md"
          git commit -m "Render README.md" || exit 0
          git push
        fi
